components:
################################################################################
  schemas:
    Users:
      type: object
      properties:
        id:
          $ref: '#/components/examples/datastoreid'
        user_email:
          $ref: '#/components/examples/email'
        user_id:
          $ref: '#/components/examples/jwtsub'
        creted_at:
          $ref: '#/components/examples/datetime'
    Exercises:
      type: object
      properties:
        id:
          $ref: '#/components/examples/datastoreid'
        exercise_name:
          $ref: '#/components/examples/name'
        video_links:
          type: array
          items:
            $ref: '#/components/examples/url'
        reference_links:
          type: array
          items:
            $ref: '#/components/examples/url'
        movements:
          type: array
          items:
            $ref: '#/components/examples/datastoreid'
        created_by:
          $ref: '#/components/examples/jwtsub'
        created_at:
          $ref: '#/components/examples/datetime'
    Movements:
      type: object
      properties:
        id:
          $ref: '#/components/examples/datastoreid'
        movement_name:
          $ref: '#/components/examples/name'
        coaching_tips:
          $ref: '#/components/examples/text'
        exercises:
          type: array
          items:
            $ref: '#/components/examples/datastoreid'
        created_by:
          $ref: '#/components/examples/jwtsub'
        created_at:
          $ref: '#/components/examples/datetime'
################################################################################
  # Reusable path, query, header and cookie parameters
  parameters:
################################################################################
  # Security scheme definitions (see Authentication)
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
################################################################################
  # Reusable request bodies
  requestBodies:
    movement:
      type: object
      properties:
        movement_name:
          $ref: '#/components/examples/name'
        coaching_tips:
          $ref: '#/components/examples/text'
    exercise:
      type: object
      properties:
        exercise_name:
          $ref: '#/components/examples/name'
        video_links:
          type: array
          items:
            $ref: '#/components/examples/url'
        reference_links:
          type: array
          items:
            $ref: '#/components/examples/url'
################################################################################
  # Reusable responses, such as 401 Unauthorized or 400 Bad Request
  responses:
    self:
      type: object
      properties:
        self:
          $ref: '#/components/examples/self'
    204:
      description: No Content
    400:
      description: Bad Request
    401:
      description: Unauthorized Error
    403:
      description: Forbidden
    404:
      description: Not Found
    406:
      description: Not Acceptable
    415:
      description: Unsupported Media Type
################################################################################
  # Reusable response headers
  headers:
################################################################################
  # Reusable examples
  examples:
    email: 
      type: string
      example: email@domain.com
    name: 
      type: string
      example: name
    url: 
      type: string
      example: http://www.website.com
    text:
      type: string
      example: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
    jwtsub:
      type: string
      example: auth0|123dacfecd06b80069190ff9
    datetime:
      type: DateTime
      example: 2022-06-04T20:44:26.817Z
    datastoreid:
      type: integer
      example: 12345
    integer:
      type: integer
      example: 1
    self:
      type: string
      example: 'http://www.api.com/canonical-resource-location'
      description: 'Canonical resource URL'
    next:
      type: string
      example: 'http://www.api.com/next-page'
      description: 'Link to next page of results'

################################################################################
  # Reusable links
  links:

################################################################################
  # Reusable callbacks
  callbacks: