# swagger-paths.yaml
# Kelley Neubauer - kelley@kelleyneubauer.com

components:
# ------------------------------------------------------------------------------
  schemas:
# ------------------------------------------------------------------------------
    Users:
      type: object
      properties:
        id:
          $ref: '#/components/examples/datastoreid'
        user_email:
          $ref: '#/components/examples/email'
        user_id:
          $ref: '#/components/examples/jwtsub'
        creted_at:
          $ref: '#/components/examples/datetime'
  # ----------
    Exercises:
      type: object
      properties:
        id:
          $ref: '#/components/examples/datastoreid'
        exercise_name:
          $ref: '#/components/examples/name'
        video_links:
          type: array
          items:
            $ref: '#/components/examples/url'
        reference_links:
          type: array
          items:
            $ref: '#/components/examples/url'
        movements:
          type: array
          items:
            $ref: '#/components/examples/datastoreid'
        created_by:
          $ref: '#/components/examples/jwtsub'
        created_at:
          $ref: '#/components/examples/datetime'
  # ----------
    Movements:
      type: object
      properties:
        id:
          $ref: '#/components/examples/datastoreid'
        movement_name:
          $ref: '#/components/examples/name'
        coaching_tips:
          $ref: '#/components/examples/text'
        exercises:
          type: array
          items:
            $ref: '#/components/examples/datastoreid'
        created_by:
          $ref: '#/components/examples/jwtsub'
        created_at:
          $ref: '#/components/examples/datetime'
# ------------------------------------------------------------------------------
  parameters:
# ------------------------------------------------------------------------------
    movement_id:
      in: path
      name: movement_id
      schema:
        type: integer
      required: true
      description: Numeric ID of the movement
    exercise_id:
      in: path
      name: exercise_id
      schema:
        type: integer
      required: true
      description: Numeric ID of the exercise
# ------------------------------------------------------------------------------
  securitySchemes:
# ------------------------------------------------------------------------------
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
# ------------------------------------------------------------------------------
  requestBodies:
# ------------------------------------------------------------------------------
    movement:
      type: object
      properties:
        movement_name:
          $ref: '#/components/examples/name'
        coaching_tips:
          $ref: '#/components/examples/text'
    exercise:
      type: object
      properties:
        exercise_name:
          $ref: '#/components/examples/name'
        video_links:
          type: array
          items:
            $ref: '#/components/examples/url'
        reference_links:
          type: array
          items:
            $ref: '#/components/examples/url'
# ------------------------------------------------------------------------------
  responses:
# ------------------------------------------------------------------------------
    self:
      type: object
      properties:
        self:
          $ref: '#/components/examples/self'
    204:
      description: No Content
    400:
      description: Bad Request
    401:
      description: Unauthorized Error
    403:
      description: Forbidden
    404:
      description: Not Found
    406:
      description: Not Acceptable
    415:
      description: Unsupported Media Type
# ------------------------------------------------------------------------------
  headers:
# ------------------------------------------------------------------------------
    Location:
      $ref: '#/components/examples/self'
# ------------------------------------------------------------------------------
  examples:
# ------------------------------------------------------------------------------
    email: 
      type: string
      example: email@domain.com
    name: 
      type: string
      example: name
    url: 
      type: string
      example: http://www.website.com
    text:
      type: string
      example: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
    jwtsub:
      type: string
      example: auth0|123dacfecd06b80069190ff9
    datetime:
      type: DateTime
      example: 2022-06-04T20:44:26.817Z
    datastoreid:
      type: integer
      example: 12345
    integer:
      type: integer
      example: 1
    self:
      type: string
      example: 'http://www.api.com/canonical-resource-location'
      description: 'Canonical resource URL'
    next:
      type: string
      example: 'http://www.api.com/next-page'
      description: 'Link to next page of results'